version: '2'
services:
  shopservice-app:
    image: shopservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopservice-postgresql:5432/shopService
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  shopservice-postgresql:
    extends:
      file: postgresql.yml
      service: shopservice-postgresql
